=> #<ActiveRecord::Associations::CollectionProxy 

[#<Wine id: 278, producer_id: 201, name: "Champalou Vouvray Les Tries (500ML) 2015", varietal_id: 41, vintage: 2015, region_id: 67, price: 0.62e2, expert_rating: 0.97e2, description: "The fruit is sorted, grape by grape, to find the b...", created_at: "2017-11-10 21:49:40", updated_at: "2017-11-10 21:49:40", expert_review: "Didier and Catherine Champalou have produced this ...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: nil, link_one: nil, store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 279, producer_id: 201, name: "Champalou Vouvray La Cuvee des Fondraux 2015", varietal_id: 41, vintage: 2015, region_id: 67, price: nil, expert_rating: 0.92e2, description: "At the end of a long, draining day, you deserve to...", created_at: "2017-11-10 21:49:40", updated_at: "2017-11-10 21:49:40", expert_review: "Mature vines (45 years old) provide the concentrat...", existing_avg_user_rating: 0.38e1, existing_avg_user_rating_count: 2, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwjbqZyXwa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 464, producer_id: 321, name: "Domaine des Lauriers Vouvray Demi-Sec 2014", varietal_id: 41, vintage: 2014, region_id: 67, price: nil, expert_rating: nil, description: "The nose is fruity with some hints of pear. The pa...", created_at: "2017-11-10 22:13:50", updated_at: "2017-11-10 22:13:50", expert_review: "N/A", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwiLiIfLwa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 477, producer_id: 325, name: "Jean-Maurice Raffault Chinon Rose 2015", varietal_id: 9, vintage: 2015, region_id: 67, price: nil, expert_rating: nil, description: "J-M Raffault's Chinon Rosé is considered the fines...", created_at: "2017-11-10 22:13:50", updated_at: "2017-11-12 19:21:56", expert_review: "N/A", existing_avg_user_rating: 0.36e1, existing_avg_user_rating_count: 4, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwix56POwa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 648, producer_id: 439, name: "Domaine Huet Vouvray Demi-Sec Haut Lieu (375ML hal...", varietal_id: 41, vintage: 2016, region_id: 67, price: 0.24e2, expert_rating: 0.96e2, description: "Taking its roots deep into the chalk soils of Vouv...", created_at: "2017-11-10 22:13:52", updated_at: "2017-11-10 22:13:52", expert_review: "This delivers a beautiful display of purity and gr...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: nil, link_one: nil, store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 649, producer_id: 439, name: "Domaine Huet Petillant Vouvray 2013", varietal_id: 8, vintage: 2013, region_id: 67, price: 0.28e2, expert_rating: nil, description: "Among the great values in sparkling wine and compe...", created_at: "2017-11-10 22:13:52", updated_at: "2017-11-10 22:13:52", expert_review: "N/A", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwjX1K_8wa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 650, producer_id: 439, name: "Domaine Huet Vouvray Le Mont Moelleux 2016", varietal_id: 41, vintage: 2016, region_id: 67, price: 0.51e2, expert_rating: 0.96e2, description: "Purchased in 1957, Le Mont lies on the esteemed Pr...", created_at: "2017-11-10 22:13:52", updated_at: "2017-11-10 22:13:52", expert_review: "Bright, even exuberant in feel, with a parade of J...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwjf8cj8wa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 651, producer_id: 439, name: "Domaine Huet Vouvray Moelleux Premiere Trie Clos d...", varietal_id: 41, vintage: 2016, region_id: 67, price: 0.68e2, expert_rating: 0.96e2, description: "A deep and vibrant color. On the nose, subtle flor...", created_at: "2017-11-10 22:13:52", updated_at: "2017-11-10 22:13:52", expert_review: "This is ripe and broad, taking a slightly more pow...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwj-le_8wa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 658, producer_id: 444, name: "Domaine de la Butte Bourgueil Mi-Pente 2015", varietal_id: 47, vintage: 2015, region_id: 67, price: 0.36e2, expert_rating: 0.91e2, description: "The Mi-Pente bottling is the domaine's most concen...", created_at: "2017-11-10 22:29:44", updated_at: "2017-11-12 19:17:34", expert_review: "Offers a grippy feel, with a brambly note working ...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwiZmNz-wa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 909, producer_id: 536, name: "Sauvion Vouvray 2012", varietal_id: 41, vintage: 2012, region_id: 67, price: nil, expert_rating: nil, description: "Amber in its youth and gold tinged after a few yea...", created_at: "2017-11-10 22:33:27", updated_at: "2017-11-10 22:33:27", expert_review: "N/A", existing_avg_user_rating: 0.3e1, existing_avg_user_rating_count: 2, upc: "", store_one: nil, link_one: nil, store_two: nil, link_two: nil, store_three: nil, link_three: nil>, ...]>


#<ActiveRecord::Associations::CollectionProxy [

#<Wine id: 469, producer_id: 321, name: "Domaine des Lauriers Vouvray Sec 2014", varietal_id: 41, vintage: 2014, region_id: 89, price: 0.19e2, expert_rating: nil, description: "On the nose the wine displays white fruit aromas, ...", created_at: "2017-11-10 22:13:50", updated_at: "2017-11-10 22:13:50", expert_review: "N/A", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwjI6cLMwa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 689, producer_id: 465, name: "Le Coeur de la Reine Touraine Sauvignon Blanc 2016", varietal_id: 23, vintage: 2016, region_id: 89, price: 0.12e2, expert_rating: nil, description: "The nose offers an intense fruit basket dominated ...", created_at: "2017-11-10 22:29:44", updated_at: "2017-11-10 22:29:44", expert_review: "N/A", existing_avg_user_rating: 0.2e1, existing_avg_user_rating_count: 1, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwinyKuGwq...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

#<Wine id: 808, producer_id: 465, name: "Le Coeur de la Reine Touraine Sauvignon Blanc 2016", varietal_id: 23, vintage: 2016, region_id: 89, price: 0.12e2, expert_rating: nil, description: "The nose offers an intense fruit basket dominated ...", created_at: "2017-11-10 22:33:27", updated_at: "2017-11-10 22:33:27", expert_review: "N/A", existing_avg_user_rating: 0.2e1, existing_avg_user_rating_count: 1, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwinyKuGwq...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>]>


#===========================
 #<ActiveRecord::Associations::CollectionProxy [

 #<Wine id: 278, producer_id: 201, name: "Champalou Vouvray Les Tries (500ML) 2015", varietal_id: 41, vintage: 2015, region_id: 67, price: 0.62e2, expert_rating: 0.97e2, description: "The fruit is sorted, grape by grape, to find the b...", created_at: "2017-11-10 21:49:40", updated_at: "2017-11-10 21:49:40", expert_review: "Didier and Catherine Champalou have produced this ...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: nil, link_one: nil, store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 279, producer_id: 201, name: "Champalou Vouvray La Cuvee des Fondraux 2015", varietal_id: 41, vintage: 2015, region_id: 67, price: nil, expert_rating: 0.92e2, description: "At the end of a long, draining day, you deserve to...", created_at: "2017-11-10 21:49:40", updated_at: "2017-11-10 21:49:40", expert_review: "Mature vines (45 years old) provide the concentrat...", existing_avg_user_rating: 0.38e1, existing_avg_user_rating_count: 2, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwjbqZyXwa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 464, producer_id: 321, name: "Domaine des Lauriers Vouvray Demi-Sec 2014", varietal_id: 41, vintage: 2014, region_id: 67, price: nil, expert_rating: nil, description: "The nose is fruity with some hints of pear. The pa...", created_at: "2017-11-10 22:13:50", updated_at: "2017-11-10 22:13:50", expert_review: "N/A", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwiLiIfLwa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 477, producer_id: 325, name: "Jean-Maurice Raffault Chinon Rose 2015", varietal_id: 9, vintage: 2015, region_id: 67, price: nil, expert_rating: nil, description: "J-M Raffault's Chinon Rosé is considered the fines...", created_at: "2017-11-10 22:13:50", updated_at: "2017-11-12 19:21:56", expert_review: "N/A", existing_avg_user_rating: 0.36e1, existing_avg_user_rating_count: 4, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwix56POwa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 648, producer_id: 439, name: "Domaine Huet Vouvray Demi-Sec Haut Lieu (375ML hal...", varietal_id: 41, vintage: 2016, region_id: 67, price: 0.24e2, expert_rating: 0.96e2, description: "Taking its roots deep into the chalk soils of Vouv...", created_at: "2017-11-10 22:13:52", updated_at: "2017-11-10 22:13:52", expert_review: "This delivers a beautiful display of purity and gr...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: nil, link_one: nil, store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 649, producer_id: 439, name: "Domaine Huet Petillant Vouvray 2013", varietal_id: 8, vintage: 2013, region_id: 67, price: 0.28e2, expert_rating: nil, description: "Among the great values in sparkling wine and compe...", created_at: "2017-11-10 22:13:52", updated_at: "2017-11-10 22:13:52", expert_review: "N/A", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwjX1K_8wa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 650, producer_id: 439, name: "Domaine Huet Vouvray Le Mont Moelleux 2016", varietal_id: 41, vintage: 2016, region_id: 67, price: 0.51e2, expert_rating: 0.96e2, description: "Purchased in 1957, Le Mont lies on the esteemed Pr...", created_at: "2017-11-10 22:13:52", updated_at: "2017-11-10 22:13:52", expert_review: "Bright, even exuberant in feel, with a parade of J...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwjf8cj8wa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 651, producer_id: 439, name: "Domaine Huet Vouvray Moelleux Premiere Trie Clos d...", varietal_id: 41, vintage: 2016, region_id: 67, price: 0.68e2, expert_rating: 0.96e2, description: "A deep and vibrant color. On the nose, subtle flor...", created_at: "2017-11-10 22:13:52", updated_at: "2017-11-10 22:13:52", expert_review: "This is ripe and broad, taking a slightly more pow...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwj-le_8wa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 658, producer_id: 444, name: "Domaine de la Butte Bourgueil Mi-Pente 2015", varietal_id: 47, vintage: 2015, region_id: 67, price: 0.36e2, expert_rating: 0.91e2, description: "The Mi-Pente bottling is the domaine's most concen...", created_at: "2017-11-10 22:29:44", updated_at: "2017-11-12 19:17:34", expert_review: "Offers a grippy feel, with a brambly note working ...", existing_avg_user_rating: 0.0, existing_avg_user_rating_count: 0, upc: "", store_one: "Link to Buy", link_one: "http://www.google.com/aclk?sa=l&ai=DChcSEwiZmNz-wa...", store_two: nil, link_two: nil, store_three: nil, link_three: nil>, 

 #<Wine id: 909, producer_id: 536, name: "Sauvion Vouvray 2012", varietal_id: 41, vintage: 2012, region_id: 67, price: nil, expert_rating: nil, description: "Amber in its youth and gold tinged after a few yea...", created_at: "2017-11-10 22:33:27", updated_at: "2017-11-10 22:33:27", expert_review: "N/A", existing_avg_user_rating: 0.3e1, existing_avg_user_rating_count: 2, upc: "", store_one: nil, link_one: nil, store_two: nil, link_two: nil, store_three: nil, link_three: nil>, ...]>